DO
$$
DECLARE
	path_to_offline_sales TEXT := 'd:\datasource_offline_for_incremental.csv';
	path_to_online_sales TEXT := 'd:\datasource_online_for_incremental.csv';
BEGIN
	EXECUTE FORMAT ($ex$
	CREATE FOREIGN TABLE IF NOT EXISTS sa_offline.ext_offline_sales_incr (
		sale_id varchar(4000),
		sale_date varchar(4000),
		prod_id varchar(4000),
		emp_id varchar(4000),
		emp_store_city_id varchar(4000),
		buyed_number varchar(4000),
		man_id varchar(4000),
		procurement_per_unit varchar(4000),
		sale_cost varchar(4000),
		paid_amount varchar(4000),
		sale_channel varchar(4000),
		product_name varchar(4000),
		product_cat_id varchar(4000),
		prod_cat_name varchar(4000),
		pr_subcat_id varchar(4000),
		pr_subcat_name varchar(4000),
		unit_gram_per_pack varchar(4000),
		man_name varchar(4000),
		man_addr varchar(4000),
		man_city_id varchar(4000),
		man_city_name varchar(4000),
		man_postal_code varchar(4000),
		man_country_id varchar(4000),
		man_country_name varchar(4000),
		man_ctry_province_id varchar(4000),
		man_ctry_province_name varchar(4000),
		man_continent_id varchar(4000),
		man_continent_name varchar(4000),
		emp_name varchar(4000),
		emp_dob varchar(4000),
		emp_email varchar(4000),
		emp_store_id varchar(4000),
		emp_store_name varchar(4000),
		store_city_id varchar(4000),
		store_addr varchar(4000),
		store_city_name varchar(4000),
		store_postal_code varchar(4000),
		store_country_id varchar(4000),
		store_country_name varchar(4000),
		store_ctry_province_id varchar(4000),
		store_ctry_province_name varchar(4000),
		store_continent_id varchar(4000),
		store_continent_name varchar(4000)
		) SERVER file_server
		OPTIONS (FORMAT 'csv', filename '%s',
		HEADER 'true', DELIMITER ',')$ex$, path_to_offline_sales);
	
	EXECUTE FORMAT ($ex$
	CREATE FOREIGN TABLE IF NOT EXISTS sa_online.ext_online_sales_incr (
		sale_id varchar(4000),
		sale_date varchar(4000),
		prod_id varchar(4000),
		customer_id varchar(4000),
		quantity_ordered varchar(4000),
		man_id varchar(4000),
		procurement_per_unit varchar(4000),
		order_cost varchar(4000),
		paid_amount varchar(4000),
		delivery_hour varchar(4000),
		sale_channel varchar(4000),
		product_name varchar(4000),
		product_cat_id varchar(4000),
		prod_cat_name varchar(4000),
		pr_subcat_id varchar(4000),
		pr_subcat_name varchar(4000),
		unit_gram_per_pack varchar(4000),
		cust_first_name varchar(4000),
		cust_last_name varchar(4000),
		cust_gender varchar(4000),
		cust_dob varchar(4000),
		cust_addr varchar(4000),
		cust_tel_number varchar(4000),
		cust_email varchar(4000),
		cust_city_id varchar(4000),
		cust_city_name varchar(4000),
		cust_postal_code varchar(4000),
		cust_country_id varchar(4000),
		cust_country_name varchar(4000),
		cust_ctry_province_id varchar(4000),
		cust_ctry_province_name varchar(4000),
		cust_continent_id varchar(4000),
		cust_continent_name varchar(4000),
		man_name varchar(4000),
		man_addr varchar(4000),
		man_city_id varchar(4000),
		man_city_name varchar(4000),
		man_postal_code varchar(4000),
		man_country_id varchar(4000),
		man_country_name varchar(4000),
		man_ctry_province_id varchar(4000),
		man_ctry_province_name varchar(4000),
		man_continent_id varchar(4000),
		man_continent_name varchar(4000)
		) SERVER file_server
		OPTIONS (FORMAT 'csv', filename '%s',
		HEADER 'true', DELIMITER ',')$ex$, path_to_online_sales);

END;
$$;

INSERT INTO sa_offline.src_offline_sales (sale_id ,
										sale_date,
										prod_id,
										emp_id,
										emp_store_city_id,
										buyed_number,
										man_id,
										procurement_per_unit,
										sale_cost,
										paid_amount,
										sale_channel,
										product_name,
										product_cat_id,
										prod_cat_name,
										pr_subcat_id,
										pr_subcat_name,
										unit_gram_per_pack,
										man_name,
										man_addr,
										man_city_id,
										man_city_name,
										man_postal_code,
										man_country_id,
										man_country_name,
										man_ctry_province_id,
										man_ctry_province_name,
										man_continent_id,
										man_continent_name,
										emp_name,
										emp_dob,
										emp_email,
										emp_store_id,
										emp_store_name,
										store_city_id,
										store_addr,
										store_city_name,
										store_postal_code,
										store_country_id,
										store_country_name,
										store_ctry_province_id,
										store_ctry_province_name,
										store_continent_id,
										store_continent_name)
										
	SELECT * FROM sa_offline.ext_offline_sales_incr
		ON CONFLICT (sale_id) DO NOTHING;
	
INSERT INTO sa_online.src_online_sales (sale_id,
										sale_date,
										prod_id,
										customer_id,
										quantity_ordered,
										man_id,
										procurement_per_unit,
										order_cost,
										paid_amount,
										delivery_hour,
										sale_channel,
										product_name,
										product_cat_id,
										prod_cat_name,
										pr_subcat_id,
										pr_subcat_name,
										unit_gram_per_pack,
										cust_first_name,
										cust_last_name,
										cust_gender,
										cust_dob,
										cust_addr,
										cust_tel_number,
										cust_email,
										cust_city_id,
										cust_city_name,
										cust_postal_code,
										cust_country_id,
										cust_country_name,
										cust_ctry_province_id,
										cust_ctry_province_name,
										cust_continent_id,
										cust_continent_name,
										man_name,
										man_addr,
										man_city_id,
										man_city_name,
										man_postal_code,
										man_country_id,
										man_country_name,
										man_ctry_province_id,
										man_ctry_province_name,
										man_continent_id,
										man_continent_name)
										
	SELECT * FROM sa_online.ext_online_sales_incr
		ON CONFLICT (sale_id) DO NOTHING;

COMMIT;